# Generated by Django 4.1.1 on 2022-09-21 12:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.user',),
            managers=[
                ('departments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.user',),
            managers=[
                ('lecturers', django.db.models.manager.Manager()),
            ],
        ),
    ]
