# Generated by Django 4.1.1 on 2022-09-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_department_lecturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
